---
version: '3'
services:
  xnbd_client:
    build:
      context: ./build
      args:
        DISTRO_VERSION: ${DISTRO_VERSION}
    image: neofob/xnbd_client:${DISTRO_VERSION}
    container_name: xnbd_client
    privileged: true
    volumes:
      - ./scripts/entrypoint.sh:/entrypoint.sh
    devices:
      - ${NBD_DEV}:${NBD_DEV}
    entrypoint:
      - /entrypoint.sh
      - ${NBD_HOST}
      - ${NBD_PORT}
      - ${NBD_DEV}
